const Data = [
  {
    id: 1,
    nombre: "ST 37",
    descrip:
      "Analiza videos deportivos en tiempo real con IA, abarca más de 25 deportes.",
    categoria: "Productividad",
    pago: "De Pago",
    img: "st37",
    url: "https://www.st37.fr/",
    bgdestacado: "pago",
  },
  {
    id: 2,
    nombre: "School Unlocked",
    descrip: "Desbloquea apps y juegos para computadoras escolares.",
    categoria: "Productividad",
    pago: "Gratis",
    img: "School-Unlocked",
    url: "https://mangoai.co/schoolunlocked/",
    bgdestacado: "gratis",
  },
  {
    id: 3,
    nombre: "Deep AI",
    descrip:
      "Genera y modifica imagenes con solo escribir el promt ideal, su renderizado es muy potente.",
    categoria: "Imagen",
    pago: "De Pago",
    img: "deepai",
    url: "https://deepai.org/",
    bgdestacado: "pago",
  },
  {
    id: 4,
    nombre: "Gemini Google",
    descrip:
      "Chat de Google con IA en la que puedes buscar o hacer cualquier cosa.",
    categoria: "Contenido",
    pago: "Gratis",
    img: "bard",
    url: "https://gemini.google.com/app",
    bgdestacado: "gratis",
  },
  {
    id: 5,
    nombre: "Mixo",
    descrip:
      "Generador de ideas para emprendimientos, te ayuda a elegir el nombre para tu nuevo negocio.",
    categoria: "Contenido",
    pago: "Freemiun",
    img: "mixo",
    url: "https://www.mixo.io/",
    bgdestacado: "freemiun",
  },
  {
    id: 6,
    nombre: "Rytr",
    descrip:
      "Generador de contenidos para tus redes sociales, tiene diferentes targets o categorías.",
    categoria: "Contenido",
    pago: "Freemiun",
    img: "rytr",
    url: "https://rytr.me/",
    bgdestacado: "freemiun",
  },
  {
    id: 7,
    nombre: "Eat This Much",
    descrip:
      "Eat This Much crea recetas y planes de alimentación basado en tus comidas favoritas, inventa tu receta.",
    categoria: "Estilo de vida",
    pago: "Freemiun",
    img: "eat",
    url: "https://www.eatthismuch.com/",
    bgdestacado: "freemiun",
  },
  {
    id: 8,
    nombre: "Road Trippers",
    descrip:
      "Planifica tu viaje de vacaciones, encuentra los mejores lugares para visitar, te crea el itenerario mas óptimo para ahorrar.",
    categoria: "Estilo de vida",
    pago: "Freemiun",
    img: "roadtrip",
    url: "https://roadtrippers.com/",
    bgdestacado: "freemiun",
  },
  {
    id: 9,
    nombre: "Claude Chat",
    descrip:
      "Claude es un asistente de IA de última generación para sus tareas, sin importar la escala.",
    categoria: "Contenido",
    pago: "Gratis",
    img: "claude",
    url: "https://claude.ai/login?selectAccount=true&returnTo=%2Fchats",
    bgdestacado: "gratis",
  },
  {
    id: 10,
    nombre: "Chat GPT",
    descrip:
      "Genera y comprende texto como un ser humano, muy avanzado a la hora de enteder lo que se le pide, analiza y entiende lo que queremos.",
    categoria: "Contenido",
    pago: "Freemiun",
    img: "chatgpt",
    url: "https://chat.openai.com/auth/login",
    bgdestacado: "freemiun",
  },
  {
    id: 11,
    nombre: "Hix AI",
    descrip:
      "120+ herramientas de escritura de IA para crear el mejor texto para contenido, blog, post de instagram.",
    categoria: "Contenido",
    pago: "De Pago",
    img: "hix",
    url: "https://hix.ai/",
    bgdestacado: "pago",
  },
  {
    id: 12,
    nombre: "Tutor AI",
    descrip:
      "Aprende a construir o aprender cualquier con tutoriales bien explicados gracias a su potente IA.",
    categoria: "Estilo de Vida",
    pago: "Gratis",
    img: "learn",
    url: "https://www.tutorai.me/",
    bgdestacado: "gratis",
  },
  {
    id: 13,
    nombre: "Monica AI",
    descrip:
      "Monica es un asistente de IA todo en uno equipado con los modelos de IA más avanzados (GPT-4, Claude, Bard, etc.) para ayudarte a Chatear, Buscar, Escribir, Traducir y más.",
    categoria: "Contenido",
    pago: "De Pago",
    img: "monica",
    url: "https://monica.im/",
    bgdestacado: "pago",
  },
  {
    id: 14,
    nombre: "Flair AI",
    descrip:
      "Diseña las fotos de tus productos con IA para tu tienda on line, solo arrastrar y soltar y tendras tu imagen del producto.",
    categoria: "Productividad",
    pago: "De Pago",
    img: "flair",
    url: "https://flair.ai/",
    bgdestacado: "pago",
  },
  {
    id: 15,
    nombre: "Texvoz",
    descrip:
      "Convierte texto a voz en pocos segundos, con voces en español y muy realistas, la version gratis soporta hasta 3mil carácteres.",
    categoria: "Audio/Video",
    pago: "Freemiun",
    img: "texvoz",
    url: "https://www.texvoz.com/",
    bgdestacado: "freemiun",
  },
  {
    id: 16,
    nombre: "Writesonic",
    descrip:
      "Generador de contenidos y chatbots, excelente para crear cualquier tipo de contenido desde un post de blog hasta instagram.",
    categoria: "Contenido",
    pago: "Freemiun",
    img: "writesonic",
    url: "https://writesonic.com/",
    bgdestacado: "freemiun",
  },
  {
    id: 18,
    nombre: "Quicktok",
    descrip:
      "Crea videos cortos con solo escirbir texto, agregale voz, editalos como quieras y demás puedes agregar tu propia voz.",
    categoria: "Audio/Video",
    pago: "De Pago",
    img: "quicktop",
    url: "https://quicktok.ai/es/",
    bgdestacado: "pago",
  },
  {
    id: 19,
    nombre: "Leonardo AI",
    descrip:
      "Uno de los mejores geneeradores de imagenes, con solo texto crea imagenes con mucha exactitud para tiktok o youtube.",
    categoria: "Imagen",
    pago: "Freemiun",
    img: "leonardoai",
    url: "https://app.leonardo.ai/",
    bgdestacado: "freemiun",
  },
  {
    id: 20,
    nombre: "HeyGen",
    descrip:
      "Crea avatares personalizados en video y agregale voz, hablará por ti en tus presentaciones de video en youtube o tiktok.",
    categoria: "Audio/Video",
    pago: "Freemiun",
    img: "heygen",
    url: "https://app.heygen.com/home",
    bgdestacado: "freemiun",
  },
  {
    id: 21,
    nombre: "Pixlr",
    descrip:
      "Generador de imagenes muy potente, con muchas ventajas, puedes modificar, gratis por medio de creditos",
    categoria: "Imagen",
    pago: "Gratis",
    img: "pixlr",
    url: "https://pixlr.com/es/image-generator/",
    bgdestacado: "gratis",
  },
  {
    id: 22,
    nombre: "PromptHero",
    descrip:
      "No sabes cómo generar esa imagen que imaginas en Midjourney? Prompthero te ayuda y te facilta, miles de promts para tu proyecto.",
    categoria: "Imagen",
    pago: "Gratis",
    img: "promthero",
    url: "https://prompthero.com/prompt/b9c4b082c1e",
    bgdestacado: "gratis",
  },
  {
    id: 23,
    nombre: "Sora",
    descrip:
      "La revolución ha llegado, Sora crea videos realistas con solo describir la situación y la acción que necesitas, debes probarla.",
    categoria: "Audio/Video",
    pago: "De Pago",
    img: "sora",
    url: "https://openai.com/sora",
    bgdestacado: "pago",
  },
  {
    id: 24,
    nombre: "Krea AI",
    descrip:
      "Genera imagenes alucinantes desde un dibujo hecho a mano, un garabato lo convierte en una obra de arte.",
    categoria: "Imagen",
    pago: "Freemiun",
    img: "kreaai",
    url: "https://www.krea.ai/home",
    bgdestacado: "freemiun",
  },
  {
    id: 25,
    nombre: "DeepL",
    descrip:
      "Traductor con IA que puede hacer su trabajo en varios idiomas a la vez, no esta disponible en algunos paises.",
    categoria: "Productividad",
    pago: "Freemiun",
    img: "deepl",
    url: "https://www.deepl.com/translator",
    bgdestacado: "freemiun",
  },
  {
    id: 26,
    nombre: "Eleven Labs",
    descrip:
      "Convierta texto a voz en línea de forma gratuita con nuestro generador de voz con IA. En cualquier idioma.",
    categoria: "Productividad",
    pago: "Freemiun",
    img: "elevenlabs",
    url: "https://elevenlabs.io/",
    bgdestacado: "freemiun",
  },
  {
    id: 27,
    nombre: "AudioStrip",
    descrip:
      "La mejor herramienta en línea utilizada por músicos para separar las voces de la música de acompañamiento en archivos de audio.",
    categoria: "Productividad",
    pago: "Freemiun",
    img: "audiostrip",
    url: "https://www.audiostrip.co.uk/",
    bgdestacado: "freemiun",
  },
  {
    id: 28,
    nombre: "Cody Para Empresas",
    descrip:
      "Cody es un asistente de IA como ChatGPT, puedes entrenarlo para tu empresa, responder preguntas, solucionar problemas y generar ideas.",
    categoria: "Productividad",
    pago: "De Pago",
    img: "cody",
    url: "https://meetcody.ai/",
    bgdestacado: "pago",
  },
  {
    id: 29,
    nombre: "Fitness AI",
    descrip:
      "FitnessAI para iPhone utiliza inteligencia artificial para generar entrenamientos personalizados.",
    categoria: "Estilo de vida",
    pago: "Gratis",
    img: "fitnessai",
    url: "https://www.fitnessai.com/",
    bgdestacado: "gratis",
  },
  {
    id: 30,
    nombre: "AI Meal Planner",
    descrip:
      "Crea deliciosos planes semanales de comidas saludables, ideal para hacer dieta y comer sano.",
    categoria: "Estilo de vida",
    pago: "Gratis",
    img: "imeal",
    url: "https://casadesante.com/pages/a-i-meal-planner",
    bgdestacado: "gratis",
  },
  {
    id: 31,
    nombre: "Chef Gpt",
    descrip:
      "No sabes que cocinar?, tienes pocos ingredientes? Chef Gpt te prepara la receta con IA y podrás hacer una rica comida.",
    categoria: "Estilo de vida",
    pago: "Freemiun",
    img: "chefgpt",
    url: "https://www.chefgpt.xyz/es?via=appsai",
    bgdestacado: "freemiun",
  },
  {
    id: 32,
    nombre: "Wonderplan",
    descrip:
      "Su planificador de viajes personal y curador de viajes, creando itinerarios personalizados adaptados a sus intereses y presupuesto.",
    categoria: "Estilo de vida",
    pago: "Gratis",
    img: "wonderplan",
    url: "https://wonderplan.ai/",
    bgdestacado: "gratis",
  },
  {
    id: 33,
    nombre: "Dream Interpreter AI",
    descrip:
      "Deseas saber el signficado de tu sueño? Con esta aplicación lo podras saber, solo escribe tu sueño y te dira lo que deseas saber.",
    categoria: "Estilo de vida",
    pago: "Gratis",
    img: "dreamia",
    url: "https://www.dreaminterpreter.ai/",
    bgdestacado: "gratis",
  },
  {
    id: 34,
    nombre: "Grok AI",
    descrip:
      "Elon Musk no se quedo atrás y ha creado su propia herramienta de IA, totalmente gratis.",
    categoria: "Productividad",
    pago: "Gratis",
    img: "grok",
    url: "https://grok.x.ai/",
    bgdestacado: "gratis",
  },
  {
    id: 35,
    nombre: "Theselyricsdonotexist",
    descrip:
      "Genera letras para canciones totalmente originales, usa la IA para generar coros y versos originales por genero, topico y humor.",
    categoria: "Estilo de vida",
    pago: "Gratis",
    img: "lyrics",
    url: "https://theselyricsdonotexist.com/",
    bgdestacado: "gratis",
  },
  {
    id: 36,
    nombre: "AI Jingle Maker",
    descrip:
      "Puedes elegir una intro, un fondo, una salida, crear tu voz en off con IA y dejar que JINGLEMAKER genere mágicamente tu jingle.",
    categoria: "Audio/Video",
    pago: "De Pago",
    img: "jinglemaker",
    url: "https://www.aijinglemaker.com/",
    bgdestacado: "pago",
  },
  {
    id: 37,
    nombre: "Render Forest",
    descrip:
      "Crea videos explicativos y promocionales formidables, intros de calidad, visualizaciones de música y mucho más.",
    categoria: "Audio/Video",
    pago: "Freemiun",
    img: "renderforest",
    url: "https://www.renderforest.com/",
    bgdestacado: "freemiun",
  },
  {
    id: 38,
    nombre: "Fliki AI",
    descrip:
      "Crea videos a partir de texto, fácil de usar con voces en off realistas, videoclips dinámicos de IA y una amplia gama de funciones.",
    categoria: "Audio/Video",
    pago: "Freemiun",
    img: "fliki",
    url: "https://fliki.ai/?via=a61aff",
    bgdestacado: "freemiun",
  },
  //{id:21,nombre:' ',descrip:' .',categoria:' ',pago:' ',img:'fitnessai',url:'https://fliki.ai/?via=a61aff',bgdestacado:''},
];

export default Data;
